[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/produtos"
  to = "/.netlify/functions/produtos"
  status = 200

[[redirects]]
  from = "/api/produtos/*"
  to = "/.netlify/functions/produtos/:splat"
  status = 200
